import type { Metadata } from "next";
// import { Inter, Poppins } from "next/font/google";
import localFont from 'next/font/local'
import "./globals.css";
import Navbar from "./NavBar";
import AuthProvider from "@/auth/provider";

// const inter = Inter({ subsets: ["latin"] });

// const poppins = Poppins({
//   subsets: ["latin"],
//   weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
// });

const poppins =localFont({
  src: '../public/Fonts/Poppins.ttf',
  variable:'--font-poppins'
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  openGraph:{
    title: '...',
    description: '...',
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="winter">
      <body className={poppins.className}>
        <AuthProvider>
          <Navbar />
          <main className="p-[2rem]">{children}</main>
        </AuthProvider>
      </body>
    </html>
  );
}
