"use client"
import Image from "next/image";
import Link from "next/link";
import { useState } from "react";
import ProductCard from "./components/productComponent/ProductCard";
import { getServerSession } from "next-auth";
import { authOption } from "./api/auth/[...nextauth]/route";
import Pic from "@/public/Picture.png"
// import HeavyComponent from "./components/HeavyComponent";

import dynamic from "next/dynamic";
const HeavyComponent = dynamic(
  () => import('./components/HeavyComponent'),
  {
    ssr: false,
    loading : () => <p>Loading ...</p>
  }
);


// export default async function Home() {
export default async function Home() {
  // const session = await getServerSession(authOption);
  const [isVisible, setVisible] = useState(false);
  return (
    <main>
      <h1>Hello world</h1>
      {/* <h1>Hello {session && <span>{session.user!.name}</span>}</h1> */}
      {/* <div className="relative h-screen">
        <Image
          src={Pic}
          fill
          alt="Mension house"
          className="object-cover"
          sizes="(max-width : 480px) 100vw, (max-width : 7680px) 50vw, 33vw"
          quality={100}
        />
      </div> */}

      {/* Using dynamic Lazy loading Lodash */}
      {/* <button onClick={async () => {
        const _ = (await import('lodash')).default;
        const users =[
          {name: 'c'},
          {name: 'b'},
          {name: 'a'},
        ]
        const sorted = _.orderBy(users,['name']);
        console.log(sorted)
      }} className="mb-12">
        Show
      </button> */}

      <button onClick={() => setVisible(!isVisible)} className="mb-12">
        Show
      </button>
      {isVisible && <HeavyComponent />}

      <ProductCard />
    </main>
  );
}


// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export async function generateMetadata(): Promise<Metadata>{
//   const product = await fetch('')

//   return {
//     title:'product.title',
//     description:'product.title'
//   }
// }
